-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 23:22:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jaf19g
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jaf19g` ;

-- -----------------------------------------------------
-- Schema jaf19g
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jaf19g` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `jaf19g` ;

-- -----------------------------------------------------
-- Table `jaf19g`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`job` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`job` (
  `job_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_title` VARCHAR(45) NOT NULL,
  `job_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jaf19g`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`employee` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`employee` (
  `emp_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` TINYINT UNSIGNED NOT NULL,
  `emp_ssn` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `emp_fname` VARCHAR(15) NOT NULL,
  `emp_lname` VARCHAR(30) NOT NULL,
  `emp_dob` DATE NOT NULL,
  `emp_start_date` DATE NOT NULL,
  `emp_end_date` DATE NULL,
  `emp_salary` DECIMAL(8,2) NOT NULL,
  `emp_street` VARCHAR(30) NOT NULL,
  `emp_city` VARCHAR(20) NOT NULL,
  `emp_state` CHAR(2) NOT NULL,
  `emp_zip` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `emp_phone` BIGINT UNSIGNED NOT NULL,
  `emp_email` VARCHAR(100) NOT NULL,
  `emp_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `fk_employee_job1_idx` (`job_id` ASC) VISIBLE,
  UNIQUE INDEX `emp_ssn_UNIQUE` (`emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_employee_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `jaf19g`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jaf19g`.`dependent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`dependent` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`dependent` (
  `dep_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `dep_added` DATE NOT NULL,
  `dep_ssn` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `dep_fname` VARCHAR(15) NOT NULL,
  `dep_lname` VARCHAR(30) NOT NULL,
  `dep_dob` DATE NOT NULL,
  `dep_relation` VARCHAR(20) NOT NULL,
  `dep_street` VARCHAR(30) NOT NULL,
  `dep_city` VARCHAR(20) NOT NULL,
  `dep_state` CHAR(2) NOT NULL,
  `dep_zip` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `dep_phone` BIGINT UNSIGNED NOT NULL,
  `dep_email` VARCHAR(100) NOT NULL,
  `dep_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`dep_id`),
  UNIQUE INDEX `dep_ssn_UNIQUE` (`dep_ssn` ASC) VISIBLE,
  INDEX `fk_dependent_employee_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_dependent_employee`
    FOREIGN KEY (`emp_id`)
    REFERENCES `jaf19g`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jaf19g`.`benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`benefit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`benefit` (
  `ben_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ben_name` VARCHAR(45) NOT NULL,
  `ben_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`ben_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jaf19g`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`plan` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`plan` (
  `pln_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `ben_id` TINYINT UNSIGNED NOT NULL,
  `pln_type` ENUM('single', 'spouse', 'family') NOT NULL,
  `pln_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pln_election_date` DATE NOT NULL,
  `pln_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pln_id`),
  INDEX `fk_plan_employee1_idx` (`emp_id` ASC) VISIBLE,
  INDEX `fk_plan_benefit1_idx` (`ben_id` ASC) VISIBLE,
  CONSTRAINT `fk_plan_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `jaf19g`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_benefit1`
    FOREIGN KEY (`ben_id`)
    REFERENCES `jaf19g`.`benefit` (`ben_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jaf19g`.`emp_hist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jaf19g`.`emp_hist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jaf19g`.`emp_hist` (
  `eht_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NULL,
  `eht_date` DATETIME NOT NULL,
  `eht_type` ENUM('i', 'u', 'd') NOT NULL,
  `eht_job_id` TINYINT UNSIGNED NOT NULL,
  `eht_emp_salary` DECIMAL(8,2) NOT NULL,
  `eht_usr_changed` VARCHAR(30) NOT NULL,
  `eht_reason` VARCHAR(45) NOT NULL,
  `eht_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`eht_id`),
  INDEX `fk_emp_hist_employee1_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_emp_hist_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `jaf19g`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jaf19g`.`job`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Chief Advisor', NULL);
INSERT INTO `jaf19g`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Secratary', NULL);
INSERT INTO `jaf19g`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Customer Specialist', NULL);
INSERT INTO `jaf19g`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Human Resources Advisor', NULL);
INSERT INTO `jaf19g`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Financial Advisor', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `jaf19g`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 1, 738935796, 'Miquela', 'Ingham', '1999-01-04', '2019-09-25', NULL, 100000.00, '6808 Hollow Ridge Alley', 'Dulles', 'VA', 864533537, 2711426125, 'mingham0@a8.net', '');
INSERT INTO `jaf19g`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 1, 329913066, 'Nicola', 'Ellesmere', '1984-10-12', '2018-08-24', NULL, 100000.00, '6628 Stang Road', 'South Bend', 'IN', 492309045, 6930098803, 'nellesmere1@newyorker.com', '');
INSERT INTO `jaf19g`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 3, 710339185, 'Happy', 'Wildey', '1986-12-23', '2002-02-13', NULL, 200000.00, '7 Tennessee Lane', 'Memphis', 'TN', 883092681, 6320367465, 'hwildey2@wikipedia.org', '');
INSERT INTO `jaf19g`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 2, 948580914, 'Gardener', 'Hull', '1989-08-01', '2018-05-25', NULL, 120000.00, '9532 Summit Court', 'San Diego', 'CA', 460418881, 1908210227, 'ghull3@slate.com', '');
INSERT INTO `jaf19g`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 5, 176488284, 'Melony', 'Haley', '1994-08-08', '2019-08-01', NULL, 150000.00, '5 Harper Circle', 'Anaheim', 'CA', 549508164, 1794282789, 'mhaley4@whitehouse.gov', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jaf19g`.`dependent`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 1, '2003-05-14', 932386494, 'Silvana', 'Wimsett', '2011-09-29', 'daughter', '44813 Hintze Street', 'Fort Worth', 'TX', 221960960, 3951921926, 'swimsett0@wikia.com', '');
INSERT INTO `jaf19g`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 2, '2002-08-06', 549188549, 'Vale', 'Duigan', '2007-09-29', 'son', '37117 Larry Crossing', 'Austin', 'TX', 429996557, 3322710946, 'vduigan1@posterous.com', '');
INSERT INTO `jaf19g`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 3, '2003-12-24', 123692303, 'Maddi', 'Andrewartha', '2008-05-30', 'spouse', '14454 Myrtle Crossing', 'Oklahoma City', 'OK', 245662195, 8785009673, 'mandrewartha2@elegantthemes.com', '');
INSERT INTO `jaf19g`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 4, '2018-10-25', 896628990, 'Coleen', 'Gorwood', '2017-09-14', 'daughter', '01 Logan Terrace', 'Austin', 'TX', 998542811, 4345644363, 'cgorwood3@addtoany.com', '');
INSERT INTO `jaf19g`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 5, '2015-08-06', 507720616, 'Zacharias', 'McKim', '2015-06-17', 'son', '41528 Graedel Street', 'Fort Wayne', 'IN', 958893133, 1869375874, 'zmckim4@stanford.edu', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jaf19g`.`benefit`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'medical', NULL);
INSERT INTO `jaf19g`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'dental', NULL);
INSERT INTO `jaf19g`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, '401k', NULL);
INSERT INTO `jaf19g`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'vision', NULL);
INSERT INTO `jaf19g`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'life insurance', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `jaf19g`.`plan`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 1, 4, 'single', 1000.00, '2022-02-02', NULL);
INSERT INTO `jaf19g`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 3, 4, 'single', 2000.00, '2021-05-08', NULL);
INSERT INTO `jaf19g`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 2, 2, 'spouse', 3000.00, '2021-04-20', NULL);
INSERT INTO `jaf19g`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 3, 3, 'family', 2000.00, '2019-08-12', NULL);
INSERT INTO `jaf19g`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 4, 4, 'spouse', 2000.00, '2018-11-11', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `jaf19g`.`emp_hist`
-- -----------------------------------------------------
START TRANSACTION;
USE `jaf19g`;
INSERT INTO `jaf19g`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 1, '2022-02-02', 'i', 1, 100000.00, 'Spouse', 'Marriage', NULL);
INSERT INTO `jaf19g`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 1, '2013-12-12', 'i', 1, 200000.00, 'Boss', 'Raise', NULL);
INSERT INTO `jaf19g`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 2, '2008-08-08', 'u', 2, 300000.00, 'Spouse', 'Marriage', NULL);
INSERT INTO `jaf19g`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 4, '2004-12-14', 'u', 3, 400000.00, 'Child', 'Birth', NULL);
INSERT INTO `jaf19g`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 3, '2005-06-08', 'd', 3, 400000.00, 'Spouse', 'Marriage', NULL);

COMMIT;